### ISSUE TITLE
AntOutDir not working

### ISSUE THREAD

**Issue by hannesN** [kaby76/Antlr4BuildTasks#27]
Hi,

for reasons I need to set the output directory for the generated files. In an older issue I found the tag "AntOutDir", however, that doesn't seem to work anymore. My code is always generated in obj/Release.

I hope you can help me.

Thanks
Hannes

**Comment by kaby76** [comment]
I can't reproduce the problem. Attached is a full dotnet console application that uses AntOutDir, placing the generated files in $(ProjectDir). By default, the generated files should go where the .obj are placed.  `dotnet clean` does not clean up the generated files completely, so that will need to be addressed.
[te.zip](https://github.com/kaby76/Antlr4BuildTasks/files/8389427/te.zip)

Could you provide an example zipped up?

**Comment by hannesN** [comment]
Thanks for the example, I had an error in my project configuration. Sorry for the additional work. Now the parser creation works. (I inherited the project and come from java programming.)
