### ISSUE TITLE
64 bit version of functions?

### ISSUE THREAD

**Issue by renzosilv** [kaby76/Antlr4BuildTasks#53]
This is more of a general question as opposed to an issue - I am using antlr4 and your build tasks library.   I am however running out of memory on large files which are more than 1G while zipped.  I was wondering if there is a way to force the libraries to use more memory - by perhaps using 64 bit equivalents?

This is the error 

```
FATAL: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder.ToString()
   at System.IO.StreamReader.ReadToEnd()
   at Antlr4.Runtime.AntlrInputStream.Load(TextReader r, Int32 size, Int32 readChunkSize)
   at Antlr4.Runtime.AntlrInputStream..ctor(TextReader r, Int32 initialSize, Int32 readChunkSize)
   at Antlr4.Runtime.AntlrInputStream..ctor(TextReader r, Int32 initialSize)
   at Antlr4.Runtime.AntlrInputStream..ctor(Stream input)
```

**Comment by kaby76** [comment]
Looks like there's a misunderstanding of the tool here. There is no call to AntlrInputStream() in Antlr4BuildTasks (other than the tests in [_tests](https://github.com/kaby76/Antlr4BuildTasks/tree/master/_tests), which are not packaged with Antlr4BuildTasks). It does not do parsing. The purpose of Antlr4BuildTasks is to run "java -jar Antlr4-4.11.1-complete.jar -Dlanguage=CSharp *.g4" when building a C# program in order to generate the parser and lexer source files that you would use in a program that you write. That way you do not need to install Java and type out on the command line "java -jar Antlr4-4.11.1-complete.jar -Dlanguage=CSharp *.g4"
