### ISSUE TITLE
I followed the readme instructions but the build is not generating classes

### ISSUE THREAD

**Issue by RamiSh** [kaby76/Antlr4BuildTasks#88]
Any thought on why my build is not generating classes? Here is my cs project file
Here is the `dotnet build -v diag > output.txt` [output.txt](https://github.com/user-attachments/files/17523162/output.txt)
```
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<Antlr4 Include="Expr.g4">
			<Listener>true</Listener>
			<Visitor>true</Visitor>
			<GAtn>true</GAtn>
			<Package>foo</Package>
			<Error>true</Error>
		</Antlr4>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="GeneratedByANTLR\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Antlr4.Runtime.Standard" Version="4.13.1" />
		<PackageReference Include="Antlr4BuildTasks" Version="12.8" PrivateAssets="all" IncludeAssets="build" />
	</ItemGroup>
</Project>
```

Here is my grammar file

```
grammar Expr;
prog:	expr EOF ;
expr:	expr ('*'|'/') expr
    |	expr ('+'|'-') expr
    |	INT
    |	'(' expr ')'
    ;
NEWLINE : [\r\n]+ -> skip;
INT     : [0-9]+ ;
```
Let me know if you need additional details. Thanks!

**Comment by kaby76** [comment]
1) `Errors: MSB4276: The default SDK resolver failed to resolve SDK "Microsoft.NET.SDK.WorkloadAutoImportPropsLocator" because directory "C:\Program Files\dotnet\sdk\8.0.403\Sdks\Microsoft.NET.SDK.WorkloadAutoImportPropsLocator\Sdk" did not exist.`.  Looks like dotnet is messed up.
1) The end of output.txt has `Build succeeded.  0 Warning(s)  0 Error(s)`. You didn't remove the obj/ and bin/ directories. So, I can't tell what happened, but it's all compiling and linking.
1) `<ItemGroup> <Folder Include="GeneratedByANTLR\" /></ItemGroup>`. What is this? You don't specify where to put the generated files this way. Get rid of the directory and all it's contents if you have anything there. The default is to put the .cs files from the Antlr Tool in the obj/ directory. It's generated code. You don't check it into git.

**Comment by RamiSh** [comment]
Just to close the loop on this ticket and to provide additional context to new comers.

The .net8 setup was fine. I closed/relaunched the solution and did a right-click Clean.

Here is my working csproj file
```
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
	  <Antlr4 Include="FilterByExpressionGrammar.g4" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Antlr4.Runtime.Standard" Version="4.13.1" />
		<PackageReference Include="Antlr4BuildTasks" Version="12.8" PrivateAssets="all" IncludeAssets="build" />
	</ItemGroup>
</Project>

```
